packages:
  - "apps/*"

settings:
  onlyBuiltDependencies:
    - esbuild
    - mongodb-memory-server
allowBuilds:
  esbuild: set this to true or false
  mongodb-memory-server: set this to true or false
